In [2]:
import numpy as np

In [3]:
k=np.arange(0,9,1)
k=k.reshape([3,3])
poo=np.random.rand(*k.shape) < 0.5
print(type(k.shape))
np.random.rand(*(3,4))
# 這個函數的目的在給他參數，這些參數會變成array的大小，比如說你給他
# np.random.rand(5,6,7)
# 他就會在0~1之間隨機取直去造出一個5x6x7的array這樣
# 所以如果你是先把你要造的array用tuple裝起來（就是一般的array用.shape的方法）
# 直接丟進去函去就會出錯，因為他的參數要是int,可是你給他tuple
# 所以你要把tuple『分配』出去
# 就是用*了啦！
# 老師的pdf有寫，在函數那邊自己去看

<class 'tuple'>


array([[0.24024403, 0.9188078 , 0.61207232, 0.67851362],
       [0.74988867, 0.38663166, 0.39607765, 0.70383413],
       [0.88222086, 0.05716893, 0.82381772, 0.15611194]])

In [4]:
poo

array([[ True,  True, False],
       [False,  True,  True],
       [False,  True, False]])

In [5]:
l=k*poo
l

array([[0, 1, 0],
       [0, 4, 5],
       [0, 7, 0]])

In [8]:
np.sqrt(l)

array([[0.        , 1.        , 0.        ],
       [0.        , 2.        , 2.23606798],
       [0.        , 2.64575131, 0.        ]])

In [14]:
k=np.arange(0,9,1)
k=k.reshape([3,3])
k

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
k/l

/Users/pao/Documents/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/Users/pao/Documents/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan,  1., inf],
       [inf,  1.,  1.],
       [inf,  1., inf]])